// example/vue2/src/views/Products.vue
<!--
 * @Date: 2025-01-22 11:03:08
 * @LastEditors: xiaoshan
 * @LastEditTime: 2025-01-22 11:03:13
 * @FilePath: /element-tag-marker/example/vue2/src/views/Products.vue
-->
<template>
    <div xx="1232"  class="products">
        <h1>产品服务</h1>
        <div xx="1232"  class="products-content">
            <div xx="1232"  class="product-card" v-for="(product, index) in products" :key="index">
                <h3>{{ product.name }}</h3>
                <p>{{ product.description }}</p>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'Products',
    data() {
        return {
            products: [
                {
                    name: '产品一',
                    description: '产品一的详细描述'
                },
                {
                    name: '产品二',
                    description: '产品二的详细描述'
                }
            ]
        }
    }
}
</script>

<style scoped>
.products {
    padding: 20px;
}

.products-content {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
    margin-top: 20px;
}

.product-card {
    padding: 20px;
    border: 1px solid #eee;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}
</style> 
 <!-- element-tag-marker: /Users/xiaoshanwen/Desktop/me/element-tag-marker/example/vue2/src/views/Products.vue -->

// example/webpack-react/src/components/Products.tsx
/*
 * @Date: 2025-01-23 13:51:22
 * @LastEditors: xiaoshan
 * @LastEditTime: 2025-01-23 14:00:26
 * @FilePath: /element-tag-marker/example/webpack-react/src/components/Products.tsx
 */
import React from 'react';

const Products = () => {
  const products = [
    {
      id: 1,
      name: '智能分析平台',
      description: '基于AI的数据分析和决策支持系统',
       image: '../assets/logo.png'
    },
    {
      id: 2,
      name: '云计算服务',
      description: '高性能、可扩展的云计算解决方案',
      image: '../assets/logo.png'
    },
    {
      id: 3,
      name: '物联网平台',
      description: '全方位的IoT设备管理和数据分析平台',
       image: '../assets/logo.png'
    }
  ];

  return (
    <section className="products" id="products">
      <h2>产品服务</h2>
      <div className="product-grid">
        {products.map(product => (
          <div key={product.id} className="product-card">
            <img src={product.image} alt={product.name} />
            <h3>{product.name}</h3>
            <p>{product.description}</p>
          </div>
        ))}
      </div>
    </section>
  );
};

export default Products;
